# fly.toml app configuration file generated for biuxbackend on 2023-06-13T16:18:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "biuxbackend"
primary_region = "eze"
kill_timeout = 5

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
